// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckForUpdate() {
  return window['go']['main']['App']['CheckForUpdate']();
}

export function DeleteConversation(arg1, arg2) {
  return window['go']['main']['App']['DeleteConversation'](arg1, arg2);
}

export function DeleteConversations(arg1) {
  return window['go']['main']['App']['DeleteConversations'](arg1);
}

export function EnsureStatusLine() {
  return window['go']['main']['App']['EnsureStatusLine']();
}

export function GetContextInfo(arg1) {
  return window['go']['main']['App']['GetContextInfo'](arg1);
}

export function GetVersion() {
  return window['go']['main']['App']['GetVersion']();
}

export function PickDirectory() {
  return window['go']['main']['App']['PickDirectory']();
}

export function RemoveWorktrees(arg1) {
  return window['go']['main']['App']['RemoveWorktrees'](arg1);
}
