// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function Activity():Promise<main.Activity>;

export function CheckForUpdate():Promise<main.UpdateInfo>;

export function DeleteConversation(arg1:string,arg2:string):Promise<void>;

export function DeleteConversations(arg1:string):Promise<main.DeleteResult>;

export function EnsureStatusLine():Promise<void>;

export function GetContextInfo(arg1:string):Promise<main.ContextInfo>;

export function GetVersion():Promise<string>;

export function PickDirectory():Promise<string>;

export function RemoveWorktrees(arg1:Array<string>):Promise<main.WorktreeCleanup>;
