// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function EnsureStatusLine() {
  return window['go']['main']['App']['EnsureStatusLine']();
}

export function GetContextInfo(arg1) {
  return window['go']['main']['App']['GetContextInfo'](arg1);
}

export function GetVersion() {
  return window['go']['main']['App']['GetVersion']();
}

export function PickDirectory() {
  return window['go']['main']['App']['PickDirectory']();
}
