// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CheckForUpdate():Promise<main.UpdateInfo>;

export function EnsureStatusLine():Promise<void>;

export function GetContextInfo(arg1:string):Promise<main.ContextInfo>;

export function GetVersion():Promise<string>;

export function PickDirectory():Promise<string>;
