// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetAgents(arg1) {
  return window['go']['main']['ClaudeService']['GetAgents'](arg1);
}

export function GetCommands(arg1) {
  return window['go']['main']['ClaudeService']['GetCommands'](arg1);
}

export function GetLastMessage(arg1) {
  return window['go']['main']['ClaudeService']['GetLastMessage'](arg1);
}

export function GetMCPServers(arg1) {
  return window['go']['main']['ClaudeService']['GetMCPServers'](arg1);
}
