// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetAgents(arg1:string):Promise<Array<main.AgentInfo>>;

export function GetCommands(arg1:string):Promise<Array<main.CommandInfo>>;

export function GetLastMessage(arg1:string):Promise<string>;

export function GetMCPServers(arg1:string):Promise<Array<main.MCPServer>>;
