// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetConfig() {
  return window['go']['main']['ConfigService']['GetConfig']();
}

export function GetSessions() {
  return window['go']['main']['ConfigService']['GetSessions']();
}

export function SaveConfig(arg1) {
  return window['go']['main']['ConfigService']['SaveConfig'](arg1);
}

export function SaveSessions(arg1) {
  return window['go']['main']['ConfigService']['SaveSessions'](arg1);
}

export function SetSlackToken(arg1) {
  return window['go']['main']['ConfigService']['SetSlackToken'](arg1);
}
