// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function EnsureAPIKey() {
  return window['go']['main']['ConfigService']['EnsureAPIKey']();
}

export function GetConfig() {
  return window['go']['main']['ConfigService']['GetConfig']();
}

export function GetHiddenPRs() {
  return window['go']['main']['ConfigService']['GetHiddenPRs']();
}

export function GetSessions() {
  return window['go']['main']['ConfigService']['GetSessions']();
}

export function HidePR(arg1, arg2) {
  return window['go']['main']['ConfigService']['HidePR'](arg1, arg2);
}

export function SaveConfig(arg1) {
  return window['go']['main']['ConfigService']['SaveConfig'](arg1);
}

export function SaveSessions(arg1) {
  return window['go']['main']['ConfigService']['SaveSessions'](arg1);
}

export function UnhidePR(arg1, arg2) {
  return window['go']['main']['ConfigService']['UnhidePR'](arg1, arg2);
}

export function WriteCLIConfig(arg1) {
  return window['go']['main']['ConfigService']['WriteCLIConfig'](arg1);
}
