// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function ApprovePR(arg1:string,arg2:number):Promise<void>;

export function FetchNotifications(arg1:string):Promise<Array<main.GitHubNotification>>;

export function FetchPRs():Promise<Array<main.GitHubPR>>;

export function MarkAllNotificationsRead():Promise<void>;

export function MarkNotificationRead(arg1:string):Promise<void>;

export function MergePR(arg1:string,arg2:number):Promise<void>;
