// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function FetchNotifications(arg1:string):Promise<Array<main.GitHubNotification>>;

export function FetchPRs():Promise<Array<main.GitHubPR>>;

export function MarkNotificationRead(arg1:string):Promise<void>;
