// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ApprovePR(arg1, arg2) {
  return window['go']['main']['GitHubService']['ApprovePR'](arg1, arg2);
}

export function FetchNotifications(arg1) {
  return window['go']['main']['GitHubService']['FetchNotifications'](arg1);
}

export function FetchPRCommits(arg1, arg2) {
  return window['go']['main']['GitHubService']['FetchPRCommits'](arg1, arg2);
}

export function FetchPRFiles(arg1, arg2) {
  return window['go']['main']['GitHubService']['FetchPRFiles'](arg1, arg2);
}

export function FetchPRReviews(arg1, arg2) {
  return window['go']['main']['GitHubService']['FetchPRReviews'](arg1, arg2);
}

export function FetchPRs() {
  return window['go']['main']['GitHubService']['FetchPRs']();
}

export function MarkAllNotificationsRead() {
  return window['go']['main']['GitHubService']['MarkAllNotificationsRead']();
}

export function MarkNotificationRead(arg1) {
  return window['go']['main']['GitHubService']['MarkNotificationRead'](arg1);
}

export function MergePR(arg1, arg2) {
  return window['go']['main']['GitHubService']['MergePR'](arg1, arg2);
}
