// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AddIssueComment(arg1:string,arg2:number,arg3:string):Promise<main.PRComment>;

export function ApprovePR(arg1:string,arg2:number):Promise<void>;

export function FetchBranchCI(arg1:string,arg2:string):Promise<main.BranchCI>;

export function FetchNotifications(arg1:string):Promise<Array<main.GitHubNotification>>;

export function FetchPRComments(arg1:string,arg2:number):Promise<main.PRCommentsData>;

export function FetchPRCommits(arg1:string,arg2:number):Promise<Array<main.PRCommit>>;

export function FetchPRFileDiff(arg1:string,arg2:number,arg3:string):Promise<main.FileDiffData>;

export function FetchPRFiles(arg1:string,arg2:number):Promise<Array<main.PRFile>>;

export function FetchPRReviews(arg1:string,arg2:number):Promise<Array<main.PRReview>>;

export function FetchPRs():Promise<Array<main.GitHubPR>>;

export function MarkAllNotificationsRead():Promise<void>;

export function MarkNotificationRead(arg1:string):Promise<void>;

export function MergePR(arg1:string,arg2:number):Promise<void>;

export function ReplyToReviewComment(arg1:string,arg2:number,arg3:number,arg4:string):Promise<main.PRComment>;
