// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function FetchNotifications(arg1) {
  return window['go']['main']['GitHubService']['FetchNotifications'](arg1);
}

export function FetchPRs() {
  return window['go']['main']['GitHubService']['FetchPRs']();
}

export function MarkNotificationRead(arg1) {
  return window['go']['main']['GitHubService']['MarkNotificationRead'](arg1);
}
