// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetBranchName(arg1) {
  return window['go']['main']['GitService']['GetBranchName'](arg1);
}

export function GetFileChanges(arg1) {
  return window['go']['main']['GitService']['GetFileChanges'](arg1);
}
