// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateWorktree(arg1, arg2, arg3, arg4) {
  return window['go']['main']['GitService']['CreateWorktree'](arg1, arg2, arg3, arg4);
}

export function GetBranchName(arg1) {
  return window['go']['main']['GitService']['GetBranchName'](arg1);
}

export function GetFileChanges(arg1) {
  return window['go']['main']['GitService']['GetFileChanges'](arg1);
}

export function GetFileContent(arg1, arg2) {
  return window['go']['main']['GitService']['GetFileContent'](arg1, arg2);
}

export function GetFileDiff(arg1, arg2, arg3) {
  return window['go']['main']['GitService']['GetFileDiff'](arg1, arg2, arg3);
}

export function GetRepoSlug(arg1) {
  return window['go']['main']['GitService']['GetRepoSlug'](arg1);
}

export function GetWorktreeForDir(arg1) {
  return window['go']['main']['GitService']['GetWorktreeForDir'](arg1);
}

export function ListWorktrees(arg1) {
  return window['go']['main']['GitService']['ListWorktrees'](arg1);
}

export function PruneWorktrees(arg1) {
  return window['go']['main']['GitService']['PruneWorktrees'](arg1);
}

export function RemoveWorktree(arg1, arg2) {
  return window['go']['main']['GitService']['RemoveWorktree'](arg1, arg2);
}
