// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetBranchName(arg1:string):Promise<string>;

export function GetFileChanges(arg1:string):Promise<Array<main.FileChange>>;

export function GetFileContent(arg1:string,arg2:string):Promise<main.FileContentData>;

export function GetFileDiff(arg1:string,arg2:string,arg3:boolean):Promise<main.FileDiffData>;
