// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function DebugFetch():Promise<string>;

export function GetMessages():Promise<Array<main.SlackMessage>>;

export function GetTeamID():Promise<string>;

export function TestConnection():Promise<string>;
