// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DebugFetch() {
  return window['go']['main']['SlackService']['DebugFetch']();
}

export function GetMessages() {
  return window['go']['main']['SlackService']['GetMessages']();
}

export function GetTeamID() {
  return window['go']['main']['SlackService']['GetTeamID']();
}

export function TestConnection() {
  return window['go']['main']['SlackService']['TestConnection']();
}
