// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CloseSession(arg1:string):Promise<void>;

export function CreateSession(arg1:string,arg2:string,arg3:number,arg4:number,arg5:boolean):Promise<string>;

export function CreateShellSession(arg1:string,arg2:number,arg3:number):Promise<string>;

export function GetSessionPID(arg1:string):Promise<number>;

export function GetSessionState(arg1:string):Promise<string>;

export function GetSessions():Promise<Array<main.SessionInfo>>;

export function ReadOutput(arg1:string):Promise<string>;

export function ReplayBuffer(arg1:string):Promise<string>;

export function Resize(arg1:string,arg2:number,arg3:number):Promise<void>;

export function Subscribe(arg1:string):Promise<any>;

export function Unsubscribe(arg1:string,arg2:any):Promise<void>;

export function Write(arg1:string,arg2:string):Promise<void>;
