// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CloseSession(arg1:string):Promise<void>;

export function CreateSession(arg1:string,arg2:string,arg3:number,arg4:number):Promise<string>;

export function GetSessions():Promise<Array<main.SessionInfo>>;

export function Resize(arg1:string,arg2:number,arg3:number):Promise<void>;

export function Write(arg1:string,arg2:string):Promise<void>;
