// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CloseSession(arg1) {
  return window['go']['main']['TerminalManager']['CloseSession'](arg1);
}

export function CreateSession(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['TerminalManager']['CreateSession'](arg1, arg2, arg3, arg4, arg5);
}

export function CreateShellSession(arg1, arg2, arg3) {
  return window['go']['main']['TerminalManager']['CreateShellSession'](arg1, arg2, arg3);
}

export function GetSessionPID(arg1) {
  return window['go']['main']['TerminalManager']['GetSessionPID'](arg1);
}

export function GetSessionState(arg1) {
  return window['go']['main']['TerminalManager']['GetSessionState'](arg1);
}

export function GetSessions() {
  return window['go']['main']['TerminalManager']['GetSessions']();
}

export function ReadOutput(arg1) {
  return window['go']['main']['TerminalManager']['ReadOutput'](arg1);
}

export function ReplayBuffer(arg1) {
  return window['go']['main']['TerminalManager']['ReplayBuffer'](arg1);
}

export function Resize(arg1, arg2, arg3) {
  return window['go']['main']['TerminalManager']['Resize'](arg1, arg2, arg3);
}

export function Subscribe(arg1) {
  return window['go']['main']['TerminalManager']['Subscribe'](arg1);
}

export function Unsubscribe(arg1, arg2) {
  return window['go']['main']['TerminalManager']['Unsubscribe'](arg1, arg2);
}

export function Write(arg1, arg2) {
  return window['go']['main']['TerminalManager']['Write'](arg1, arg2);
}
