// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Check(arg1) {
  return window['go']['main']['WorkerService']['Check'](arg1);
}

export function GetConfig() {
  return window['go']['main']['WorkerService']['GetConfig']();
}

export function ReadLog(arg1) {
  return window['go']['main']['WorkerService']['ReadLog'](arg1);
}

export function RunNow(arg1, arg2) {
  return window['go']['main']['WorkerService']['RunNow'](arg1, arg2);
}

export function SaveConfig(arg1) {
  return window['go']['main']['WorkerService']['SaveConfig'](arg1);
}

export function SetEnabled(arg1) {
  return window['go']['main']['WorkerService']['SetEnabled'](arg1);
}

export function Status() {
  return window['go']['main']['WorkerService']['Status']();
}
