// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Check(arg1:string):Promise<string>;

export function GetConfig():Promise<string>;

export function ReadLog(arg1:number):Promise<string>;

export function RunNow(arg1:string,arg2:boolean):Promise<string>;

export function SaveConfig(arg1:string):Promise<void>;

export function SetEnabled(arg1:boolean):Promise<void>;

export function Status():Promise<string>;
